# Generated by Django 4.0.6 on 2022-07-19 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('types', models.CharField(choices=[('NM', 'Normal'), ('FR', 'Fire'), ('FT', 'Fighting'), ('FL', 'Flying'), ('GR', 'Grass'), ('PS', 'Poison'), ('GN', 'Ground'), ('PY', 'Psychic'), ('RC', 'Rock'), ('IC', 'Ice'), ('BG', 'Bug'), ('DR', 'Dragon'), ('GH', 'Ghost'), ('DR', 'Dark'), ('ST', 'Steel'), ('FR', 'Fairy')], max_length=100)),
                ('height', models.FloatField(blank=True, null=True)),
                ('wight', models.FloatField(blank=True, null=True)),
                ('captured', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pokemons', models.ManyToManyField(to='pokedex.pokemon')),
            ],
        ),
    ]
