# Generated by Django 4.0.6 on 2022-07-19 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('type_1', models.CharField(choices=[('BG', 'Bug'), ('DR', 'Dark'), ('DR', 'Dragon'), ('EL', 'Electric'), ('FL', 'Flying'), ('FR', 'Fairy'), ('FR', 'Fire'), ('FT', 'Fighting'), ('GH', 'Ghost'), ('GN', 'Ground'), ('GR', 'Grass'), ('IC', 'Ice'), ('NM', 'Normal'), ('PS', 'Poison'), ('PY', 'Psychic'), ('RC', 'Rock'), ('ST', 'Steel'), ('WT', 'Water')], max_length=100)),
                ('type_2', models.CharField(blank=True, choices=[('BG', 'Bug'), ('DR', 'Dark'), ('DR', 'Dragon'), ('EL', 'Electric'), ('FL', 'Flying'), ('FR', 'Fairy'), ('FR', 'Fire'), ('FT', 'Fighting'), ('GH', 'Ghost'), ('GN', 'Ground'), ('GR', 'Grass'), ('IC', 'Ice'), ('NM', 'Normal'), ('PS', 'Poison'), ('PY', 'Psychic'), ('RC', 'Rock'), ('ST', 'Steel'), ('WT', 'Water')], max_length=100, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('found', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite'],
            },
        ),
    ]
