# Generated by Django 4.0.6 on 2022-07-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokedex',
            name='pokemons',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokedex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokedex'),
        ),
    ]
