# Generated by Django 4.0.6 on 2022-07-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_remove_pokedex_pokemons_pokemon_pokedex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='wight',
            new_name='weight',
        ),
    ]
