# Generated by Django 4.0.6 on 2022-07-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemon_is_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['is_favorite']},
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.CharField(choices=[('NM', 'Normal'), ('FR', 'Fire'), ('FT', 'Fighting'), ('FL', 'Flying'), ('GR', 'Grass'), ('PS', 'Poison'), ('GN', 'Ground'), ('PY', 'Psychic'), ('RC', 'Rock'), ('IC', 'Ice'), ('BG', 'Bug'), ('DR', 'Dragon'), ('GH', 'Ghost'), ('DR', 'Dark'), ('ST', 'Steel'), ('FR', 'Fairy'), ('WT', 'Water')], max_length=100),
        ),
    ]
