# Generated by Django 4.0.6 on 2022-07-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_pokemon_options_alter_pokemon_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='types',
            new_name='type_1',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type_2',
            field=models.CharField(blank=True, choices=[('BG', 'Bug'), ('DR', 'Dark'), ('DR', 'Dragon'), ('EL', 'Electric'), ('FL', 'Flying'), ('FR', 'Fairy'), ('FR', 'Fire'), ('FT', 'Fighting'), ('GH', 'Ghost'), ('GN', 'Ground'), ('GR', 'Grass'), ('IC', 'Ice'), ('NM', 'Normal'), ('PS', 'Poison'), ('PY', 'Psychic'), ('RC', 'Rock'), ('ST', 'Steel'), ('WT', 'Water')], max_length=100, null=True),
        ),
    ]
