# Generated by Django 4.0.6 on 2022-07-19 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokedex', '0007_rename_types_pokemon_type_1_pokemon_type_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='pokedex',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pokedex',
        ),
    ]
